# Import Libraries

In [29]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load Data

In [30]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [31]:
df.shape

(569, 33)

In [32]:
df.drop(columns={"id", "Unnamed: 32"}, inplace=True)

In [33]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [34]:
X = df.iloc[:,1:]

In [35]:
y = df.iloc[:,0]

# Split Data

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

### Feature Scaling

In [37]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [38]:
X_train

array([[ 0.733758  ,  0.02274066,  0.64417335, ..., -0.46570517,
        -0.61783536, -1.33127265],
       [-0.48692915, -0.17443243, -0.46416038, ..., -0.20373669,
         0.19593028,  0.22148321],
       [-0.4422358 ,  0.32079301, -0.42114193, ..., -0.06618031,
        -1.12079933,  0.0739211 ],
       ...,
       [ 1.8203651 ,  2.69604096,  1.75210125, ...,  0.78055563,
        -0.04803232, -0.0758768 ],
       [ 0.53543126,  0.30245133,  0.63199832, ...,  1.41331498,
         1.35224613,  1.71387276],
       [-0.56793585, -0.34867842, -0.59808573, ..., -0.85605961,
        -1.11912836, -0.54651051]])

### Label Encoding

In [39]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [40]:
y_train

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0])

In [41]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [42]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [43]:
X_train_tensor.dtype

torch.float64

In [44]:
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

### Why `float64` → `float32`?
* PyTorch's neural network layers (`nn.Linear`) use `float32` by default, while Pandas/NumPy often provide `float64`.
* Converting to `float32` avoids dtype mismatch errors and is faster and more memory-efficient.

# Defining Model by PyTorch nn Module

In [45]:
class MySimpleNN(nn.Module):

    def __init__(self,num_features):

      super().__init__() # call parent constructor
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)

      return out


# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Important Parameters

In [46]:
learning_rate = 0.1
epochs = 25

# Define the Loss Function and Optimizer

In [47]:
# define loss function
loss_function = nn.BCELoss()

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Trainig PipeLine

In [48]:
batch_size = 45
n_samples = len(X_train_tensor)

In [49]:
# Step - 1 define loop for epoch
for epoch in range(epochs):

    # Step - 2 Manual Mini-Batch
    for start_idx in range(0,n_samples,batch_size):
        end_idx = start_idx + batch_size
        X_batch = X_train_tensor[start_idx:end_idx]
        y_batch = y_train_tensor[start_idx:end_idx]

        # Step - 3 forward pass
        y_pred = model(X_batch)

        # Step - 4 loss calculate
        loss = loss_function(y_pred,y_batch.reshape(-1, 1))

        # Step - 5 Zero gradients
        optimizer.zero_grad()

        # Step - 6 backward pass
        loss.backward()

        # Step - 7 parameter update
        optimizer.step()

    print(f"epoch: {epoch + 1}, loss: {loss}")

epoch: 1, loss: 0.17189982533454895
epoch: 2, loss: 0.10296754539012909
epoch: 3, loss: 0.07453032582998276
epoch: 4, loss: 0.058313071727752686
epoch: 5, loss: 0.047725655138492584
epoch: 6, loss: 0.040258411318063736
epoch: 7, loss: 0.034713663160800934
epoch: 8, loss: 0.030439887195825577
epoch: 9, loss: 0.02705044485628605
epoch: 10, loss: 0.02430080994963646
epoch: 11, loss: 0.022028673440217972
epoch: 12, loss: 0.020122088491916656
epoch: 13, loss: 0.01850125566124916
epoch: 14, loss: 0.017107870429754257
epoch: 15, loss: 0.01589835062623024
epoch: 16, loss: 0.01483943872153759
epoch: 17, loss: 0.013905389234423637
epoch: 18, loss: 0.013075867667794228
epoch: 19, loss: 0.012334771454334259
epoch: 20, loss: 0.011669053696095943
epoch: 21, loss: 0.011068062856793404
epoch: 22, loss: 0.010523040778934956
epoch: 23, loss: 0.010026737116277218
epoch: 24, loss: 0.009573103860020638
epoch: 25, loss: 0.009156975895166397

### Problems with Manual Data Handling

1. **No Standard Interface**  
   Data is accessed manually using tensors and indexes. `Dataset` provides a standard way to access samples using `__len__()` and `__getitem__()`.

2. **No Easy Transformations**  
   Preprocessing and transformations have to be handled manually. `Dataset` allows transformations to be applied automatically when data is loaded.

3. **Shuffling & Sampling**  
   Data is processed in the same order unless we manually shuffle it. `DataLoader` provides `shuffle=True` and sampling support.

4. **Batch Management & Parallelization**  
   We manually create batches using `start_idx` and `end_idx`. `DataLoader` automatically creates batches and can load data in parallel using `num_workers`.

### In Short
`Dataset` → manages and preprocesses individual data samples.  
`DataLoader` → handles batching, shuffling, sampling, and parallel data loading.

# Dataset & DataLoader

Dataset and DataLoader are core abstractions in PyTorch that decouple how you define your data from how you efficiently iterate over it in training loops.

In [50]:
from torch.utils.data import Dataset, DataLoader

Create custome dataset class

In [51]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):

        self.features = features
        self.labels = labels

    def __len__(self):

        return self.features.shape[0]

    def __getitem__(self, index):

        return self.features[index], self.labels[index]

create object of custom dataset class

In [52]:
dataset = CustomDataset(X_train_tensor, y_train_tensor)

In [53]:
len(dataset)

455

In [54]:
dataset[2]

(tensor([-0.4422,  0.3208, -0.4211, -0.5112,  0.2221,  0.3315,  0.2235,  0.2823,
         -0.2856,  1.1242, -0.2416,  1.0784, -0.0967, -0.4373,  1.9900,  0.8904,
          0.6226,  1.7862,  0.1126,  0.7645, -0.6202, -0.0311, -0.5546, -0.6297,
         -0.1598, -0.1733, -0.2330, -0.0662, -1.1208,  0.0739]),
 tensor(0.))

create object of DataLoader class

In [55]:
dataloader = DataLoader(dataset, batch_size=45, shuffle=True)

In [56]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*80)

tensor([[ 0.1053,  0.7610,  0.1568,  ..., -0.0662, -1.0673, -0.1955],
        [-0.4031,  0.4698, -0.4264,  ..., -1.0256, -1.1993, -0.8288],
        [ 0.1388,  0.5111,  0.1227,  ...,  1.0480,  1.3389,  1.4456],
        ...,
        [-0.5009, -0.9906, -0.5648,  ..., -1.1358,  0.0071, -0.8780],
        [-0.2271,  0.2658, -0.1578,  ...,  1.3797,  1.1501,  1.5294],
        [ 1.4125,  1.6299,  1.4356,  ...,  0.9731,  1.2954,  1.6077]])
tensor([0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1.])
--------------------------------------------------------------------------------
tensor([[ 1.1444, -0.1790,  1.0581,  ...,  0.6461,  0.5168, -0.7913],
        [-0.8221, -0.8852, -0.7771,  ..., -0.4908, -1.2361,  1.1605],
        [ 0.3595,  0.3942,  0.4210,  ...,  1.5065,  0.1775,  1.1885],
        ...,
        [-0.4171, -1.2795, -0.4362,  ..., -0.7856, -0.8818, -0.8003],
        [-1.3814, -1.4882, -1.2596,  ..., -0.1885,  0.2360,  2.3287],
        [ 1.7841,  2.2856,  1.9307,  ...,  2.2952,  1.9889,  2.2616]])
tensor([1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 1.])
--------------------------------------------------------------------------------
tensor([[ 0.1807,  0.8825,  0.3195,  ...,  0.8845,  0.1725,  0.1941],
        [-0.1406,  0.3368, -0.0944,  ...,  0.6231,  0.5000,  1.7642],
        [ 1.9991, -0.9769,  1.9794,  ...,  1.2498, -0.2786,  0.1745],
        ...,
        [ 0.0522,  1.7492, -0.0112,  ..., -0.9048, -0.9220, -1.0563],
        [ 1.8204,  2.6960,  1.7521,  ...,  0.7806, -0.0480, -0.0759],
        [-0.7299, -0.2295, -0.7568,  ..., -0.4883,  0.5234, -0.2743]])
tensor([1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0.])
--------------------------------------------------------------------------------
tensor([[-0.7607, -1.0938, -0.7523,  ..., -0.6193,  0.0739,  0.4618],
        [-0.9953,  1.3433, -0.9950,  ..., -0.8172,  0.8560, -0.1156],
        [ 0.7170, -0.1286,  0.6807,  ...,  0.4978, -0.1449, -0.6292],
        ...,
        [-0.0512,  0.4331, -0.1111,  ..., -0.5380, -1.1208, -0.4118],
        [ 1.5299,  0.4331,  1.5208,  ...,  1.9590,  1.1968,  0.2260],
        [-0.5903, -0.3762, -0.5867,  ..., -0.7974,  0.2544, -0.7114]])
tensor([0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 1., 0.])
--------------------------------------------------------------------------------
tensor([[-0.2635, -0.5367, -0.3237,  ..., -0.2759, -0.6529, -0.4085],
        [-0.0931, -0.7339, -0.1687,  ..., -1.0616, -0.5928, -0.9674],
        [-0.1350,  0.7449,  0.0435,  ...,  1.6196,  1.1684,  3.3292],
        ...,
        [-0.7383, -0.0736, -0.7438,  ..., -0.7365,  0.2310, -0.0390],
        [-0.3780, -0.3120, -0.3789,  ..., -0.5437, -0.1967, -0.2436],
        [-0.3501, -0.2455, -0.3388,  ..., -0.7451,  0.5184, -0.6186]])
tensor([0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0.])
--------------------------------------------------------------------------------
tensor([[ 1.7505,  0.4813,  1.6222,  ...,  0.4535, -1.1007, -0.6857],
        [-0.1014, -0.4931, -0.1659,  ..., -0.9750, -0.8902, -0.6549],
        [ 1.0662, -0.5757,  1.0135,  ...,  0.5910, -0.0915, -0.0720],
        ...,
        [-1.5761, -1.4354, -1.5421,  ..., -0.4541,  0.1441,  1.1941],
        [-0.6489,  0.4148, -0.6549,  ..., -0.4921,  0.2979, -0.5605],
        [ 1.7757, -0.3647,  1.6385,  ...,  1.0878, -0.2452,  0.3064]])
tensor([1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1.,
        1., 0., 1., 0., 0., 1., 0., 0., 1.])
--------------------------------------------------------------------------------
tensor([[-0.7299,  1.1760, -0.7426,  ..., -1.0191,  0.5803, -0.8992],
        [-0.5177, -0.1882, -0.5486,  ..., -0.4648,  0.1441, -0.6533],
        [-1.1043, -1.6372, -1.0867,  ..., -0.7316,  0.0673, -0.3531],
        ...,
        [ 0.1835,  0.1947,  0.1458,  ..., -0.2007, -0.8818, -0.9808],
        [-0.0763, -1.4194, -0.0900,  ..., -0.2037, -1.2311, -0.6153],
        [-0.8221, -1.4675, -0.7860,  ...,  0.2594,  0.7457,  0.4814]])
tensor([0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
        1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0.])
--------------------------------------------------------------------------------
tensor([[-0.5987, -1.3575, -0.5965,  ..., -0.6251, -0.1934, -0.1687],
        [-0.2942,  0.2704, -0.3436,  ..., -1.1139, -0.3505, -0.5169],
        [ 0.0131,  0.0663,  0.2152,  ...,  0.5452, -0.8334,  1.3785],
        ...,
        [-0.9255, -1.4675, -0.9674,  ..., -1.1509, -0.2653, -0.3738],
        [-0.4450, -0.5069, -0.4832,  ..., -0.2494,  0.6237, -0.5722],
        [-1.0875, -0.6903, -1.1046,  ..., -1.3912, -0.3605, -0.5337]])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        1., 0., 0., 0., 1., 0., 0., 0., 0.])
--------------------------------------------------------------------------------
tensor([[ 0.4293,  0.2039,  0.4088,  ...,  0.5054,  1.8318,  1.2779],
        [ 0.4041,  0.8802,  0.7172,  ...,  2.0079,  0.6354,  1.0264],
        [-0.5596, -0.3074, -0.5770,  ..., -0.4056,  0.5368, -0.4940],
        ...,
        [-0.1154, -0.8187, -0.0851,  ...,  0.3587, -0.5142,  1.0879],
        [-0.9367,  0.4859, -0.9747,  ..., -1.7551, -0.7331, -0.9847],
        [ 1.7952, -0.4610,  1.7156,  ...,  1.4729, -0.3471, -0.7259]])
tensor([1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
        1., 1., 1., 0., 1., 1., 1., 0., 1.])
--------------------------------------------------------------------------------
tensor([[-0.1210, -0.8187, -0.1687,  ..., -1.2489, -1.7340, -0.8629],
        [ 1.0159, -1.4056,  0.8958,  ..., -0.4802, -1.8610, -1.3877],
        [ 1.7114,  0.4927,  1.7602,  ...,  2.3487,  4.4469,  1.0543],
        ...,
        [-0.4283,  1.0269, -0.3992,  ...,  0.8677,  0.8125,  1.0934],
        [-0.9143, -0.1767, -0.8984,  ..., -0.5496, -1.0790, -0.3475],
        [ 2.5131,  1.7446,  2.4745,  ...,  2.2081,  0.3446,  0.1807]])
tensor([0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 1.])
--------------------------------------------------------------------------------
tensor([[-0.6378, -1.9375, -0.6650, -0.6161, -0.5317, -0.9831, -0.7852, -0.8005,
         -0.7891, -1.0083, -0.5570, -0.3030, -0.5990, -0.4692, -0.3027, -0.7739,
         -0.5835, -0.9641, -1.1833, -0.7115, -0.5242, -0.8994, -0.5946, -0.5225,
          0.2160, -0.6198, -0.5762, -0.7041, -0.7298, -0.6102],
        [-0.2104,  2.0289, -0.2694, -0.2839, -1.4944, -1.0822, -0.9526, -0.9745,
         -1.4654, -0.6987, -0.8483, -0.1116, -0.7168, -0.5535, -0.7225, -0.7745,
         -0.7860, -1.0690, -0.7554, -0.7748, -0.3424,  1.6240, -0.3162, -0.3652,
         -0.9332, -0.6979, -0.9284, -0.8715, -0.3388, -0.7226],
        [ 1.1863, -0.1928,  1.1596,  1.1428,  0.1802,  0.0320,  0.5621,  0.9933,
          1.2059, -0.3374,  1.0077,  0.4806,  0.8828,  0.8171, -0.2020, -0.5130,
         -0.1205,  0.3804,  0.3920, -0.0170,  1.3411,  0.3289,  1.3036,  1.2271,
          0.3197, -0.2798,  0.2269,  0.7546,  1.3339,  0.1259],
        [ 1.3651,  1.5887,  1.4843,  1.3014,  1.7972,  1.4488,  1.3170,  2.5041,
         -0.6651,  1.3390,  0.3759,  3.0958,  1.3648,  0.5355,  0.1637,  2.0679,
         -0.3381,  1.0600,  1.2403,  2.4106,  0.8099,  1.1500,  0.9831,  0.7006,
          0.2938,  0.2018, -0.1275,  1.0587, -0.9788,  0.4747],
        [-0.0456,  1.7858, -0.0466, -0.1774,  0.2192,  0.1722, -0.5524, -0.1577,
         -1.0295, -0.1296, -0.1643,  0.5116, -0.0130, -0.2420,  0.0653,  0.0905,
         -0.3585,  0.7113,  0.0335,  0.5497, -0.2178,  1.2233, -0.2253, -0.3202,
         -0.3586, -0.1641, -0.6681, -0.1533, -1.0807, -0.0183]])
tensor([0., 0., 1., 1., 0.])
--------------------------------------------------------------------------------