# Import Libraries

In [34]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load Data

In [35]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [36]:
df.shape

(569, 33)

In [37]:
df.drop(columns={"id", "Unnamed: 32"}, inplace=True)

In [38]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [39]:
x = df.iloc[:,1:]

In [40]:
y = df.iloc[:,0]

# Split Data

In [41]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

### Feature Scaling

In [42]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [43]:
X_train

array([[ 0.6772766 ,  0.19660906,  0.72746682, ...,  1.36436172,
         0.2454776 ,  0.66028152],
       [ 0.10052254,  1.35549079,  0.16178975, ...,  0.09346541,
         0.46201444,  1.06521335],
       [-0.32552192,  0.60269261, -0.18667403, ...,  1.40264173,
         2.40107741,  1.3442803 ],
       ...,
       [-0.32842018, -1.19974844, -0.33008512, ..., -0.85587882,
        -0.76719845,  0.98547994],
       [ 1.30040285,  0.22985566,  1.26421007, ...,  0.52985752,
        -0.91535523, -0.53458061],
       [ 0.30919738, -1.44197372,  0.23894659, ..., -0.49941537,
        -0.67765314, -0.90761908]])

### Label Encoding

In [44]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [45]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0])

In [46]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [47]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [48]:
X_train_tensor.dtype

torch.float64

In [49]:
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

# Data Preparation (Dataset & DataLoader)

In [ ]:
from torch.utils.data import Dataset, DataLoader

# Create custom dataset class
class CustomDataset(Dataset):

    def __init__(self, features, labels):

        self.features = features
        self.labels = labels

    def __len__(self):

        return self.features.shape[0]

    def __getitem__(self, index):

        return self.features[index], self.labels[index]

# create object of custom dataset class
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

# create object of DataLoader class

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# Define the Network Architecture

In [51]:
class MySimpleNN(nn.Module):

    def __init__(self,num_features):

      super().__init__() # call parent constructor
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)

      return out

model = MySimpleNN(X_train_tensor.shape[1])

# Important Parameters

In [52]:
learning_rate = 0.1
epochs = 25

# Define the Loss Function and Optimizer

In [53]:
# define loss function
loss_function = nn.BCELoss()

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Construct the Training Loop

In [54]:
# Step - 1 define loop for epoch
for epoch in range(epochs):

  # Step - 2 Mini-Batch
  for batch_features, batch_labels in train_loader:

    # Step - 3 forward pass
    y_pred = model(X_train_tensor)

    # Step - 4 loss calculate
    loss = loss_function(y_pred,y_train_tensor.reshape(-1, 1))

    # Step - 5 Zero gradients
    optimizer.zero_grad()

    # Step - 6 backward pass
    loss.backward()

    # Step - 7 parameter update
    optimizer.step()

  print(f"epoch: {epoch + 1}, loss: {loss}")

epoch: 1, loss: 0.22918449342250824
epoch: 2, loss: 0.16585592925548553
epoch: 3, loss: 0.13945360481739044
epoch: 4, loss: 0.1244320496916771
epoch: 5, loss: 0.11456288397312164
epoch: 6, loss: 0.10750238597393036
epoch: 7, loss: 0.10215701907873154
epoch: 8, loss: 0.0979432463645935
epoch: 9, loss: 0.09451929479837418
epoch: 10, loss: 0.09167075157165527
epoch: 11, loss: 0.08925580978393555
epoch: 12, loss: 0.0871766060590744
epoch: 13, loss: 0.08536334335803986
epoch: 14, loss: 0.0837646871805191
epoch: 15, loss: 0.08234208822250366
epoch: 16, loss: 0.08106586337089539
epoch: 17, loss: 0.07991287857294083
epoch: 18, loss: 0.07886471599340439
epoch: 19, loss: 0.07790656387805939
epoch: 20, loss: 0.0770263522863388
epoch: 21, loss: 0.07621414214372635
epoch: 22, loss: 0.07546164840459824
epoch: 23, loss: 0.07476194947957993
epoch: 24, loss: 0.07410913705825806
epoch: 25, loss: 0.07349824160337448

# Evaluation

In [55]:
# model evalution
model.eval()
accuracy_list=[]
with torch.no_grad():

  for batch_features, batch_labels in test_loader:

    y_pred = model.forward(batch_features)
    y_pred = (y_pred >  0.9).float()

    # calculate accuracy for current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

Accuracy: 0.9609