# Import all Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load DataSet

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns={"id", "Unnamed: 32"}, inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Split data

In [6]:
x = df.iloc[:,1:]

In [7]:
y = df.iloc[:,0]

# Split Data

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

# Feature Engineering

### Scaling

In [9]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [10]:
X_train

array([[-0.07386241, -0.53669363, -0.03934915, ...,  0.78545617,
         1.16821001,  1.27340301],
       [ 1.03415612, -1.40853466,  0.91191812, ..., -0.44247221,
        -1.83011992, -1.37802934],
       [-0.33767635, -0.67807326, -0.37857009, ..., -0.45834737,
         0.18445909, -0.77234083],
       ...,
       [-1.20492995,  0.17256082, -1.20026543, ..., -1.33507534,
        -1.58499387,  0.37329819],
       [-0.10440929,  1.0750341 , -0.1367293 , ..., -0.77719838,
        -0.40157074, -1.12519091],
       [-0.65703006,  0.56371112, -0.6928424 , ..., -1.135288  ,
        -0.77494155, -0.98922002]])

### Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [12]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [13]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

# Numpy ndarray to Pytorch tensor

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

# Defining the Model

In [16]:
class MySimpleNN:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X ,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon = 1e-8  # To prevent log(0)
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y * torch.log(y_pred) + (1 - y)* torch.log(1-y_pred)).mean()
        return loss

$$L = -\frac{1}{N} \sum_{i=1}^{N} [y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i)]$$

# Important Parameter

In [17]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# Step - 1 create model
model = MySimpleNN(X_train_tensor)

# Step - 2 define loop for epoch
for epoch in range(epochs):

    # Step - 3 forward pass
    y_pred = model.forward(X_train_tensor)

    # Step - 4 loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)

    # Step - 5 backward pass
    loss.backward()

    # Step - 6 parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Step - 7 Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"epoch: {epoch + 1}, loss: {loss}")

epoch: 1, loss: 3.6729037691066866
epoch: 2, loss: 3.542225637050406
epoch: 3, loss: 3.407731383633956
epoch: 4, loss: 3.267537491411463
epoch: 5, loss: 3.1196380340140153
epoch: 6, loss: 2.96807298900473
epoch: 7, loss: 2.8107019718661532
epoch: 8, loss: 2.645741396463241
epoch: 9, loss: 2.4763699301862774
epoch: 10, loss: 2.3006711417864505
epoch: 11, loss: 2.1246326970840435
epoch: 12, loss: 1.9495267129498748
epoch: 13, loss: 1.7826517147410401
epoch: 14, loss: 1.6237486548034934
epoch: 15, loss: 1.4740517355562321
epoch: 16, loss: 1.3381143948730188
epoch: 17, loss: 1.2178676065305525
epoch: 18, loss: 1.1149285407803133
epoch: 19, loss: 1.0300865660067158
epoch: 20, loss: 0.9627699874614611
epoch: 21, loss: 0.9109523672674452
epoch: 22, loss: 0.8717846698760072
epoch: 23, loss: 0.8424042657669614
epoch: 24, loss: 0.8202790735422215
epoch: 25, loss: 0.8033184294348593

In [19]:
model.weights

tensor([[-0.0333],
        [ 0.1513],
        [ 0.0325],
        [ 0.2873],
        [-0.2995],
        [ 0.2438],
        [ 0.1067],
        [ 0.0760],
        [ 0.0178],
        [ 0.4948],
        [-0.2606],
        [-0.0569],
        [-0.0375],
        [-0.1575],
        [ 0.1086],
        [-0.1481],
        [-0.4394],
        [-0.0023],
        [ 0.4764],
        [ 0.3749],
        [ 0.0454],
        [ 0.3887],
        [-0.1407],
        [ 0.2659],
        [-0.1886],
        [ 0.2002],
        [ 0.0176],
        [-0.4651],
        [ 0.2882],
        [-0.0235]], dtype=torch.float64, requires_grad=True)

In [20]:
model.bias

tensor([-0.1344], dtype=torch.float64, requires_grad=True)

# Evalution

In [22]:
# model evalution
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >  0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)

tensor(0.5897)