# Import Libraries

In [35]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load Data

In [36]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [37]:
df.shape

(569, 33)

In [38]:
df.drop(columns={"id", "Unnamed: 32"}, inplace=True)

In [39]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
x = df.iloc[:,1:]

In [41]:
y = df.iloc[:,0]

# Split Data

In [42]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

### Feature Scaling

In [43]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [44]:
X_train

array([[-1.10046517, -1.05097096, -1.10782698, ..., -1.35613823,
         1.01806627, -0.21131636],
       [-0.85583756, -1.0390982 , -0.85816952, ..., -0.72041171,
         0.44778011, -0.61428487],
       [-0.62808083, -0.43833686, -0.65950418, ..., -0.3570959 ,
         0.28552968, -0.76821554],
       ...,
       [ 0.38698313, -1.76096164,  0.44029406, ...,  1.03312761,
         0.47027027,  0.93216862],
       [-0.3047225 ,  0.350014  , -0.33437837, ..., -0.79015129,
         0.43814147, -1.0826739 ],
       [ 0.11704923, -1.99841672,  0.10496982, ...,  0.11037247,
        -0.05503557, -0.2190129 ]])

### Label Encoding

In [45]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [46]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0])

In [47]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [48]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [49]:
X_train_tensor.dtype

torch.float64

In [50]:
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

### Why `float64` → `float32`?
* PyTorch's neural network layers (`nn.Linear`) use `float32` by default, while Pandas/NumPy often provide `float64`.
* Converting to `float32` avoids dtype mismatch errors and is faster and more memory-efficient.

# Important Parameters

In [51]:
learning_rate = 0.1
epochs = 25

# Loss Function 

Setting up the loss function (to measure error)

In [52]:
# define loss function
loss_function = nn.BCELoss()

# Defining Model by PyTorch nn Module

In [53]:
class MySimpleNN(nn.Module):

    def __init__(self,num_features):

      super().__init__() # call parent constructor
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)

      return out

# Trainig PipeLine

* `y_pred` is `(455, 1)` because the Linear layer has 1 output neuron.
* `y_train_tensor` is `(455,)` because the original target is a 1D array.
* So we reshape it to `(455, 1)` to match `y_pred` before calculating the loss.

### Model Calling

Passing features to the model to get predictions (forward pass).

In [54]:
# Step - 1 create model
model = MySimpleNN(X_train_tensor.shape[1])

# Step - 2 define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Step - 3 define loop for epoch
for epoch in range(epochs):

    # Step - 4 forward pass
    y_pred = model(X_train_tensor)

    # Step - 5 loss calculate
    loss = loss_function(y_pred,y_train_tensor.reshape(-1, 1))

    # Step - 6 Zero gradients
    optimizer.zero_grad()

    # Step - 7 backward pass
    loss.backward()

    # Step - 8 parameter update
    optimizer.step()

    print(f"epoch: {epoch + 1}, loss: {loss}")

epoch: 1, loss: 0.7136224508285522
epoch: 2, loss: 0.5416045188903809
epoch: 3, loss: 0.450260192155838
epoch: 4, loss: 0.39335039258003235
epoch: 5, loss: 0.3539107143878937
epoch: 6, loss: 0.32463932037353516
epoch: 7, loss: 0.3018663823604584
epoch: 8, loss: 0.28353151679039
epoch: 9, loss: 0.2683808505535126
epoch: 10, loss: 0.25560301542282104
epoch: 11, loss: 0.24464765191078186
epoch: 12, loss: 0.2351265847682953
epoch: 13, loss: 0.22675752639770508
epoch: 14, loss: 0.21932967007160187
epoch: 15, loss: 0.21268212795257568
epoch: 16, loss: 0.206689715385437
epoch: 17, loss: 0.20125342905521393
epoch: 18, loss: 0.1962938904762268
epoch: 19, loss: 0.19174650311470032
epoch: 20, loss: 0.18755824863910675
epoch: 21, loss: 0.1836850792169571
epoch: 22, loss: 0.18009008467197418
epoch: 23, loss: 0.1767420768737793
epoch: 24, loss: 0.1736145168542862
epoch: 25, loss: 0.17068468034267426

In [55]:
print(model.linear.weight)
print()
print(model.linear.bias)

Parameter containing:
tensor([[ 0.2786,  0.2396,  0.4016,  0.1542,  0.1823, -0.0224,  0.1969,  0.3253,
          0.0086,  0.0932,  0.2861, -0.0673,  0.1047,  0.0804,  0.0570,  0.0754,
          0.0632,  0.2278, -0.1248, -0.2278,  0.1520,  0.3206,  0.1852,  0.3971,
          0.2787,  0.1194,  0.2908,  0.0920,  0.1159, -0.0695]],
       requires_grad=True)

Parameter containing:
tensor([-0.1479], requires_grad=True)

# Evaluation

In [58]:
# model evalution
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >  0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)

tensor(0.5665)